spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
payload:
  json:
    max-size-search: 50
    max-size-excel: 100
    max-size-pdf: 60
    search-values:
      array-value: "$['root-value']['inner-value'][*]['array-value']"
      case-urn: "$['unknown-attribute']"

