spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
payload:
  json:
    max-size-search: 50
    max-size-excel: 100
    max-size-pdf: 60
    search-values:
      array-value: "$['root-value']['inner-value'][*]['array-value']"
      case-urn: "$['unknown-attribute']"

