java:
  aadIdentityName: pip
  ingressHost: pip-data-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8090
  image: 'sdshmctspublic.azurecr.io/pip/data-management:latest'

  #  Uncomment once the vault containing the app insights key has been set up
  #  keyVaults:
  #    rpe:
  #      secrets:
  #        - name: AppInsightsInstrumentationKey
  #          alias: azure.application-insights.instrumentation-key
  environment:
